version: "3.7"
services:
  fabfed-webgme:
    restart: always
    image: fabfed-webgme:v1
    ports:
      - "8888:8888"
    depends_on:
      - mongo
    pull_policy: never

  mongo:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
